Repository EchoNet-Capstone/nova-nest, pull requests merged in 2025-02, with the labels that each got.

#23 Database creation
  .gitignore
  NestUi/Gui/nui_menu_bar.py
  NestUi/Utils/nest_db.py
  NestUi/__main__.py
  README.md
  found.txt
  required-linux-packages.txt
  requirements.txt
  run
  setup
  setup_in/burd_db_setup.sql
  setup_in/nestui_py_requirements.txt
  setup_in/possible_libs_not_found.txt
  setup_in/postgres_burd_db_settings.txt
  setup_in/required_linux_packages.txt
  setup_mac
Labels: enhancement, software, SBC

#25 Local db api update
  .gitignore
  NestUi/Utils/nest_db.py
  NestUi/__main__.py
  NestUi/prisma/schema.prisma
  NestUi/prisma/seed.py
  run
  run_mac
  setup
  setup_in/burd_db_setup.sql
  setup_in/nestui_py_requirements.txt
  setup_in/required_mac_packages.txt
  setup_mac
Labels: enhancement

#26 added ability to send user entered ascii data via serial connection
  NestUi/Gui/nui_menu_bar.py
  NestUi/Gui/nui_serial.py
  NestUi/Utils/nest_serial.py
Labels: enhancement, software, MCU

#27 Marker Click on Map --> Status Bar
  .gitignore
  NestUi/Gui/__init__.py
  NestUi/Gui/nui_burd_status_main_widget.py
  NestUi/Gui/nui_geo_map.py
  NestUi/Gui/nui_main_widget.py
  NestUi/Gui/nui_main_window.py
  NestUi/Utils/js/mapInteractions.js
  NestUi/Utils/nest_map.py
  NestUi/__main__.py
Labels: software

#28 Modified Serial Packet sender to send a FLOC packet.
  NestUi/Gui/nui_menu_bar.py
  NestUi/Gui/nui_send_command.py
  NestUi/Gui/nui_serial.py
  NestUi/Utils/nest_serial.py
Labels: enhancement, software, SBC, MCU, FLOC
